// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const borderWidths = {
 "thinLine": "1px",
 "medLine": "2px"
} as const;

export default borderWidths;