// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const colors = {
"primary":"#ffffff",
"primary2":"#F4F2F8",
"secondary":"#2F50C1",
"secodary2":"#4561DB",
"secondary3":"#4169E1",
"gray":"#757281",
"black":"#000000",
"independence":"#58536E",
"azuWhite":"#D9E6FD",

} as const;

export default colors;
