// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontSizes = {
 "h1": "24px",
 "h2": "20px",
 "h3": "18px",
 "h4": "16px",
 "paragraph": "14px",
} as const;

export default fontSizes;