// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const radii = {
 "easy":"6px",
 "hard": "8px",
 "rounded": "14px",
 "soft": "18px",
 "circle": "100px"
} as const;

export default radii;