// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const shadows = {
 "soft": "0px 6px 32px rgba(15, 14, 14, 0.06)",
 "medium": "0px 4px 15px rgba(15, 14, 14, 0.12)",
 "colored": "4px 8px 24px rgba(51, 150, 227, 0.25)"
} as const;

export default shadows;