// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const spacing = {
 "extraSmall": "6px",
 "tiny": "8px",
 "med": "16px",
 "med2": "20px",
 "large": "30px",
 "xlarge": "40px",
 "xxlarge": "50px"
} as const;

export default spacing;